### ISSUE TITLE
Errors in documentation on payzen.eu

### ISSUE THREAD

**Issue by nqb** [lyra/plugin-odoo#13]
Hello,

I saw several errors in documentation published on https://payzen.io/fr-FR/module-de-paiement-gratuit/#odoo

* page 3: missing reference to compatibility with Odoo 14
* page 4: missing reference to compatibility with Odoo 14
* page 7: module file is ' PayZen_Odoo_10-13_v1.2.x.zip' must be 'PayZen_Odoo_10-14_v1.2.1.zip'
* page 8: idem as on page 7

**Comment by nberhouche** [comment]
Hello,

Thank your for reporting this issue, I will inform the support team so that it will be corrected as soon as possible.

Best regards.
