### ISSUE TITLE
Documentation payzen -> lyra

### ISSUE THREAD

**Issue by petrus-v** [lyra/plugin-odoo#15]
in chapter 7.1 of this documentation https://payzen.io/files/module/doc/eu/PayZen_Odoo_10-14_v1.2_fr.pdf the ipn url should be ``http://www.your-domain.com/lyra/payzen/ipn`` instead of ``http://www.your-domain.com/payment/payzen/ipn``

Also module should be renamed in few place from payment_~~payzen~~ to payment_**lyra**

**Comment by nabil509** [comment]
Hi @petrus-v,

Please be sure you are consulting the right plugin documentation. From our code source, we generate both Lyra Collect and PayZen plugins for our two different offers.

You can consult the official doc of Lyra Collect plugin from here: https://docs.lyra.com/fr/collect/plugins/#odoo

The IPN is as displayed in the doc: http://www.your-domain.com/payment/lyra/ipn

**Comment by petrus-v** [comment]
@nabil509 ok right I didn't notice this differences

I'm closing them
