### ISSUE TITLE
Not available for Odoo 11 and 12 (Python 3)

### ISSUE THREAD

**Issue by zeroheure** [lyra/plugin-odoo#3]
This wonderful plugins should be rewrited in Python 3 to use it on new versions of Odoo.

**Comment by nabil509** [comment]
Hi, 

We started new version of the plugin 1.1.0. It will be compatible with Odoo 11 and 12. We try to make it available for the end of March.

**Comment by zeroheure** [comment]
Wow! many thanks ! Let me know if I can test earlier to entegrate in my setup.

**Comment by jpmorton** [comment]
Hi,
Do you think the new version (compatble with Odoo 12) will be available soon ? 
many thanks
regards

**Comment by nabil509** [comment]
Hi, 

We just published the release version of our plugin. We made many updates not planned initially. Please download the PayZen package on the release tab.

I close this issue.
