### ISSUE TITLE
please publish plugin on Odoo store

### ISSUE THREAD

**Issue by zeroheure** [lyra/plugin-odoo#4]
Please publish plugin on Odoo store https://www.odoo.com/apps because it is hard to know which payment options are available with Odoo.

**Comment by zeroheure** [comment]
Nothing new about this ?
Publishing on Odoo store is completely free. It will give more visibility to your payment plugin.

**Comment by GIMALima** [comment]
Hello,

Thank you for your feedback.
We gonna publish it as soon as possible.

Best regards.
