### ISSUE TITLE
documentation talks about PHP instead of Python

### ISSUE THREAD

**Issue by zeroheure** [lyra/plugin-odoo#5]
In both english and french PDF documentation available in download, at the end of PREQUISITES chapter, there is a paragraph about PHP version.
It should be removed as it can confuse end users.

**Comment by nabil509** [comment]
Hi,

Thank you. I report issue to documentation service. It will be fixed in the next version.

**Comment by nabil509** [comment]
Error fixed in version 1.2.0. I close this issue, thank you.
