### ISSUE TITLE
some typos in french documentation

### ISSUE THREAD

**Issue by zeroheure** [lyra/plugin-odoo#6]
_Il est forte**mm**ent recommandé de sélectionner la valeur Lyra._
à corriger en 
_Il est forte**m**ent recommandé de sélectionner la valeur Lyra._
(un seul **m** à _fortement_)

**Comment by zeroheure** [comment]
dans chapître **5.2 Installation du module**, point 4 :
_4. Mettre à jour le cache des applications Odoo, il faudra:_
à corriger en
_4. Mettre à jour le cache des applications Odoo, il faudra soit:_
sinon les points suivants sont redondants.
(je n'ai pas vérifié la version anglaise)

**Comment by nabil509** [comment]
Bonjour, 

Merci pour ces remontées. J'ai remonté les remarques au service concerné.
Nous prendrons en compte le premier point pour la prochaine version. Pour le 2e point, nous préférons laisser comme cela. En effet, lors des mises à jour les deux manipulations s'avèrent nécessaires. L'utilisateur n'a pas grand-chose à perdre s'il fait les deux.

Merci encore.

**Comment by zeroheure** [comment]
> L'utilisateur n'a pas grand-chose à perdre s'il fait les deux.

tout à fait
