### ISSUE TITLE
port to new API #13

### ISSUE THREAD

**Issue by zeroheure** [lyra/plugin-odoo#7]
The upcoming Odoo 13 removes deprecated API (model_cr, ...).
Odoo 13 updates a lot of ecommerce related things, add some free modules and focus toward small retailers — as you can see in the roadmap https://github.com/odoo/odoo/issues/28179.
Please update your module.

**Comment by zeroheure** [comment]
We are working on it. Quite finished now.

**Comment by nabil509** [comment]
Hi @zeroheure 

Thank you for reporting and sorry for the late response.

For efficiency reasons, we cannot work on compatibility with unstable CMS versions. We started to work on this issue after Odoo 13 was released.

So, we are finalizing a new version of our plugin including "the payment in installments" feature. This version is compatible with Odoo 13. It is available in this repository on branch feature/PLUGINS-489-payment-in-installments. You can start testing it if your are interested.

Let us know if encounter any problems.

Best regards.

**Comment by zeroheure** [comment]
Hello Nabil,

I've myself started to port the plugin to Odoo 13, ended up in paying someone who did the job. I should have send the patch. 
I will test your plugin, thanks a lot.
Best regards
Xavier

**Comment by nabil509** [comment]
Hi, 

Plugin v1.2.1 is now compatible with Odoo 14. I close this issue. You can create a new issue if this do not reply to your request.
